language: php
php:
  - 8.3
  - 8.4

matrix:
  fast_finish: true

git:
  depth: 10

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

install:
  - composer self-update
  - composer install --prefer-source --no-interaction

after_success:
  - php vendor/bin/coveralls -v

script:
  - vendor/bin/phpunit
